// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pddfeomddkrpneenmfqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkZGZlb21kZGtycG5lZW5tZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDUxOTIsImV4cCI6MjA1OTg4MTE5Mn0.PHRbGeJBniVKPOqXKdc17mSOiKCOMYRFmawXviDeqjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);